// CPC Palette with HW values
// Generated by mkts_om v0.8.20220528
// Copyleft 2017-2022 by The Mojon Twins

const unsigned char my_inks [] = {
	0x1F, // FF8080FF
	0x14, // FF000000
	0x04, // FF000080
	0x05, // FFFF0080
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14  // FF000000
};

