// CPC Palette with HW values
// Generated by mkts_om v0.3.20200505
// Copyleft 2017 by The Mojon Twins

const unsigned char my_inks [] = {
	0x0A, // FFFFFF00
	0x18, // FF800080
	0x1D, // FF8000FF
	0x04, // FF000080
	0x00, // FF808080
	0x14, // FF000000
	0x0B, // FFFFFFFF
	0x17, // FF0080FF
	0x15, // FF0000FF
	0x1A, // FF80FF00
	0x16, // FF008000
	0x1C, // FF800000
	0x0E, // FFFF8000
	0x07, // FFFF8080
	0x05, // FFFF0080
	0x0C  // FFFF0000
};

