// CPC Palette with HW values
// Generated by mkts_om v0.6.20210822
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks [] = {
	0x1A, // FF80FF00
	0x04, // FF000080
	0x18, // FF800080
	0x15, // FF0000FF
	0x1D, // FF8000FF
	0x1F, // FF8080FF
	0x1B, // FF80FFFF
	0x05, // FFFF0080
	0x07, // FFFF8080
	0x0F, // FFFF80FF
	0x0D, // FFFF00FF
	0x16, // FF008000
	0x14, // FF000000
	0x03, // FFFFFF80
	0x0E, // FFFF8000
	0x0B  // FFFFFFFF
};

