// CPC Palette with HW values
// Generated by mkts_om v0.8.20220528
// Copyleft 2017-2022 by The Mojon Twins

const unsigned char my_inks [] = {
	0x14, // FF000000
	0x15, // FF0000FF
	0x0E, // FFFF8000
	0x0B, // FFFFFFFF
	0x1C, // FF800000
	0x15, // FF0000FF
	0x0E, // FFFF8000
	0x0B, // FFFFFFFF
	0x1D, // FF8000FF
	0x15, // FF0000FF
	0x0E, // FFFF8000
	0x0B, // FFFFFFFF
	0x1F, // FF8080FF
	0x15, // FF0000FF
	0x0E, // FFFF8000
	0x0B  // FFFFFFFF
};

