// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated from ..\mus\instrumentos.asm
// Generated by wyztrackerparser v0.1 20200515

extern unsigned char tabla_pautas [0];
extern unsigned char tabla_sonidos [0];

#asm
     
    ; Tabla de instrumentos 
    ._tabla_pautas
        defw PAUTA_0,PAUTA_1,PAUTA_2,PAUTA_3,PAUTA_4,PAUTA_5 
     
    ; Tabla de efectos 
    ._tabla_sonidos
        defw SONIDO0,SONIDO1,SONIDO2,SONIDO3 
     
    ;Pautas (instrumentos) 
    ;Instrumento 'Piano' 
    .PAUTA_0
        defb 47,0,15,0,13,0,11,0,4,0,129 
    ;Instrumento 'PICC' 
    .PAUTA_1
        defb 76,0,13,0,12,0,11,0,10,0,8,0,7,0,5,0,1,0,129 
    ;Instrumento 'Flauta vol bajo' 
    .PAUTA_2
        defb 12,0,9,0,7,0,9,0,11,0,9,0,10,0,10,0,8,0,10,0,129 
    ;Instrumento 'Flauta' 
    .PAUTA_3
        defb 10,0,12,0,13,0,13,0,13,0,12,0,11,0,11,0,11,0,10,0,10,0,10,0,10,0,10,0,9,0,9,0,9,0,9,0,9,0,138 
    ;Instrumento 'Picc vol 2' 
    .PAUTA_4
        defb 65,0,2,0,3,0,4,0,5,0,129 
    ;Instrumento 'Eco' 
    .PAUTA_5
        defb 6,0,8,0,9,0,8,0,7,0,6,0,129 
     
    ;Efectos 
    ;Efecto 'bass drum' 
    .SONIDO0
        defb 209,62,0,186,92,0,255 
    ;Efecto 'drum' 
    .SONIDO1
        defb 139,46,0,232,43,8,255 
    ;Efecto 'hithat' 
    .SONIDO2
        defb 0,11,1,0,6,1,255 
    ;Efecto 'bass drum vol 2' 
    .SONIDO3
        defb 186,58,0,0,102,0,162,131,0,255 
     
    ;Frecuencias para las notas 
#endasm
