// CPC Palette with HW values
// Generated by mkts_om v0.8.20220528
// Copyleft 2017-2022 by The Mojon Twins

const unsigned char my_inks [] = {
	0x03, // FFFFFF80
	0x14, // FF000000
	0x04, // FF000080
	0x15, // FF0000FF
	0x06, // FF008080
	0x00, // FF808080
	0x1B, // FF80FFFF
	0x1A, // FF80FF00
	0x16, // FF008000
	0x1C, // FF800000
	0x0C, // FFFF0000
	0x0E, // FFFF8000
	0x0F, // FFFF80FF
	0x0D, // FFFF00FF
	0x18, // FF800080
	0x0B  // FFFFFFFF
};

