// CPC Palette with HW values
// Generated by mkts_om v0.3.20200505
// Copyleft 2017 by The Mojon Twins

const unsigned char my_inks [] = {
	0x0D, // FFFF00FF
	0x0D, // FFFF00FF
	0x0D, // FFFF00FF
	0x0D, // FFFF00FF
	0x04, // FF000080
	0x04, // FF000080
	0x04, // FF000080
	0x04, // FF000080
	0x15, // FF0000FF
	0x15, // FF0000FF
	0x15, // FF0000FF
	0x15, // FF0000FF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B  // FFFFFFFF
};

