// CPC Palette with HW values
// Generated by mkts_om v0.3.20200505
// Copyleft 2017 by The Mojon Twins

const unsigned char my_inks [] = {
	0x1C, // FF800000
	0x14, // FF000000
	0x12, // FF00FF00
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B  // FFFFFFFF
};

