// CPC Palette with HW values
// Generated by mkts_om v0.3.20200505
// Copyleft 2017 by The Mojon Twins

const unsigned char my_inks_2 [] = {
	0x0D, // FFFF00FF
	0x04, // FF000080
	0x15, // FF0000FF
	0x1B, // FF80FFFF
	0x17, // FF0080FF
	0x13, // FF00FFFF
	0x1F, // FF8080FF
	0x06, // FF008080
	0x04, // FF000080
	0x15, // FF0000FF
	0x1D, // FF8000FF
	0x0D, // FFFF00FF
	0x1E, // FF808000
	0x00, // FF808080
	0x14, // FF000000
	0x0A  // FFFFFF00
};

