// CPC Palette with HW values
// Generated by mkts_om v0.4.20210327
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks_4 [] = {
	0x0D, // FFFF00FF
	0x04, // FF000080
	0x15, // FF0000FF
	0x1B, // FF80FFFF
	0x16, // FF008000
	0x12, // FF00FF00
	0x1F, // FF8080FF
	0x06, // FF008080
	0x04, // FF000080
	0x15, // FF0000FF
	0x1D, // FF8000FF
	0x0D, // FFFF00FF
	0x1E, // FF808000
	0x00, // FF808080
	0x14, // FF000000
	0x0A  // FFFFFF00
};

