// CPC Palette with HW values
// Generated by mkts_om v0.5.20210614
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks_3 [] = {
	0x0D, // FFFF00FF
	0x04, // FF000080
	0x15, // FF0000FF
	0x03, // FFFFFF80
	0x16, // FF008000
	0x00, // FF808080
	0x13, // FF00FFFF
	0x06, // FF008080
	0x1C, // FF800000
	0x05, // FFFF0080
	0x07, // FFFF8080
	0x1D, // FF8000FF
	0x1E, // FF808000
	0x00, // FF808080
	0x14, // FF000000
	0x0A  // FFFFFF00
};

